Layout fixes
memecimeters/memecimetro pull request #14
Opened 2017-05-10 19:40 UTC by franciscod

2017-05-11 17:36 UTC, baldosa commented
mergear esto no jode con tup?

2017-05-15 02:45 UTC, baldosa requested changes
dis

2017-05-15 05:03 UTC, franciscod commented
ahora rebaseo encima de tup

2017-05-15 05:07 UTC, franciscod commented
ahi rebasee encima de master, pls review again

2017-05-18 00:15 UTC, franciscod commented
???

2017-05-18 00:20 UTC, baldosa commented
es porke te odio

2017-05-22 13:47 UTC, closed without merging

2017-05-22 13:48 UTC, baldosa commented
fixed en #26