Sleep mode
memecimeters/memecimetro pull request #21
Opened 2017-05-14 03:03 UTC by smarbos

sleepThreshold se configura en el archivo _layout.h y es la cantidad de segundos que espera el memeduino antes de dormirse desde la ultima acción que realizo*.

Setie buttonPin en el pin digital 12,  cuando le mando una señal alta, se ejecuta la función  registerActionTime() que lo que hace es guardar en una variable el momento en segundos en que sucedió la acción. Esta funcion deberíamos llamarla cada vez que un sensor sensa algo, así cuando paras la bici, se apaga solo el memeduino, no?

Tambien setie wakePin en el pin digital, lo tengo conectado a VCC, cuando el memeduino se apaga, desconecto y conecto el cable, para volverlo a prender. Esto lo remplazaríamos con un boton, pero para meme-testear funciona.

Agregue también unas funciones tipo helpers:

currentTime() {
  Devuelve el tiempo actual en segundos.
}

int currentSeconds() {
  Devuelve los segundos actuales
}

int currentMinutes() {
  devuelve los minutos actuales
}

int currentHours() {
 No la probé, pero debería devolver las horas actuales.
}

2017-05-15 05:31 UTC, franciscod requested changes
Me gusta todo pero estaria bueno que este en un archivo aparte (no mezclado con la ui). Hay una pavadita del nombre de una constante y algo que nos puede dar dolores de cabeza de como se nombran las interrupciones (cambia con cada modelo de atmega y con cada placa de arduino)

btw no lo compile ni lo testee en ningun lado

2017-05-15 05:31 UTC, franciscod commented on code/src/ema_layout.h
> +#define sleepThreshold 30
una pavada: mantegamos la convencion de CONSTANTES_EN_MAYUSCULAS, y capaz estaria bueno ponerle la unidad (segundos?) en el nombre de la variable. onda "SLEEP_THRESHOLD_SECS" o algo asi

2017-05-15 05:31 UTC, franciscod commented on code/src/ui_unny.h
> +void wakeUpNow();
faltan unos prototipos (currentMillis y sus amigos)

2017-05-15 05:31 UTC, franciscod commented on code/src/ui_unny.h
> +void wakeUpNow();
no van en este archivo, ups, no dije nada

2017-05-15 05:31 UTC, franciscod commented on code/src/ui_unny.cpp
> +}
estaría bueno que este codigo de manejo de interrupciones estuviera en un .cpp aparte, así podemos refactorear la UI o tener otra variante sin referenciar acá el codigo del timer y sleep

2017-05-15 05:31 UTC, franciscod commented on code/src/main.cpp
> +  attachInterrupt(0, wakeUpNow, LOW);
esto attachea a int(0) no? no conviene usar digitalPinToInterrupt? (https://www.arduino.cc/en/Reference/AttachInterrupt)

me preocupa que en diferentes arduinos (nano, mega2560, (uno? mini pro?)) nos de dolores de cabeza el tema del pinout.

acá hay unos diagramas re copados: http://www.pighixxx.com/test/pinoutspg/boards/

por ejemplo, en el [nano](http://www.pighixxx.com/test/wp-content/uploads/2014/11/nano.png) INT0 está en el pin digital 2 (D2), y en el [mega](http://www.pighixxx.com/test/wp-content/uploads/2014/11/mega.png) esta en el pin 21.

también estaria bueno que Ema pueda probar esto con el  "shield" que se hizo para conectar el nano y la pantalla, hay algun pin del nano que tenga interrupciones en esa fila @baldosa ?

acciones concretas a tomar que se me ocurren:
- opcion 1: dejar asi int0 directamente y documentar qué pines son para cada arduino
- opcion 2: poner un #ifdef o algo así que testee contra alguna variable que dependa del target(mega/nano/???) y con eso elegir un pin (o interrupcion) distinta para cada uno. si no hay ninguna le podriamos agregar una modificando el Tupfile

2017-05-15 05:31 UTC, franciscod commented on code/src/unny_layout.h
> +#define sleepThreshold 10
esto esta repetido

2017-05-15 05:31 UTC, franciscod commented on code/src/unny_layout.h
> +#define sleepThreshold 10
o sea, es algo que dependa de la UI?

2017-05-15 14:26 UTC, smarbos commented on code/src/unny_layout.h
> +#define sleepThreshold 10
No depende de la UI. Pero es un parámetro "configurable por el usuario", no sabia bien donde meterlo. Por eso lo puse acá.

2017-05-15 14:27 UTC, smarbos commented on code/src/main.cpp
> +  attachInterrupt(0, wakeUpNow, LOW);
Tiene sentido hacer tanto quilombo para pensar en todas las placas? O deberíamos ajustarnos al nano pro, o al que vayamos a usar, comprarlos y usar esos?
No se realmente.

2017-05-15 14:28 UTC, smarbos commented on code/src/ema_layout.h
> +#define sleepThreshold 30
OK!

2017-05-15 19:15 UTC, baldosa commented on code/src/main.cpp
> +  attachInterrupt(0, wakeUpNow, LOW);
no entendo ke tendría que ver sobre los pines im down
el mini pro 5v es un 328, pensemos todo para un 328 o un mini pro y documentamos ke sería que hay que tocar, croe ke es más fácil

2017-05-15 19:32 UTC, smarbos commented
Cada placa usa un pin para "despertar" el arduino cuando esta dormido.
Varian los pines, segun la placa.
Pero si en el codigo decimos "int0" es "int0" para todas las placas, lo que
cambia es que pin corresponde a int0 en cada placa.
Creo que es mejor así. no?
Pero si, tiene que quedar documentado cual usar en cada caso, por las dudas.

On Mon, May 15, 2017 at 4:15 PM, Ema <notifications@github.com> wrote:

> *@baldosa* commented on this pull request.
> ------------------------------
>
> In code/src/main.cpp
> <https://github.com/franciscod/memecimetro/pull/21#discussion_r116577302>:
>
> > @@ -27,6 +28,10 @@ void setup()
>    reedCounter = maxReedCounter;
>    circumference = 2*3.14*radius;
>    pinMode(reed, INPUT_PULLUP);
> +  pinMode(buttonPin, INPUT);
> +  pinMode(wakePin, INPUT);
> +  digitalWrite(9, LOW);
> +  attachInterrupt(0, wakeUpNow, LOW);
>
> no entendo ke tendría que ver sobre los pines im down
> el mini pro 5v es un 328, pensemos todo para un 328 o un mini pro y
> documentamos ke sería que hay que tocar, croe ke es más fácil
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/franciscod/memecimetro/pull/21#discussion_r116577302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJLoo2UE2ZumXH22SUflseWV2xzYnMjOks5r6KRNgaJpZM4NaQhG>
> .
>

2017-05-15 19:46 UTC, franciscod commented
si, creo que lo mas simple va a ser dejarle int0 y cablearselo al pin que corresponda en cada placa

2017-05-17 02:48 UTC, smarbos commented
# Clock:
## clock.h
## clock.cpp
* currentTime: Return the amount of seconds since the arduino starts. This number freezes when the memecimetro falls asleep.
* currentHours(): Return an integer for current hour.
* currentMinutes():  Return an integer for current minutes.
* currentSeconds():  Return an integer for current seconds.

# Sleep:
## sleep.h
## sleep.cpp
* wakeUpNow: Turn the screen's backlight ON and register an action (registerActionTime).
* sleepNow(): Clear all pixels in the display, turn off the lcd's backlight, and put the meme to sleep.
* checkSleepTime():  If current time is greater or equal the lastActionTime time plus the SLEEP_TIME_THRESHOLD, calls sleepNow().
* registerActionTime():  Save current time in seconds in a variable called lastActionTime.

# Config file:
## le_wild_vars.h
This file contains variables salvajes. 
* SLEEP_THRESHOLD_SECS: Is the amount of time the memecimetro waits before entering sleep, before the last registered action.
*BACKLIGHT_PIN: Is the pin number conected to the LCD.

2017-05-17 02:57 UTC, franciscod commented on code/src/ema_layout.h
> +#define sleepThreshold 30
esto esta para volar no? ya tenemos el posta en el vars.h

2017-05-17 02:58 UTC, franciscod approved these changes
re ok. gracias por acomodarlo 😀 let the good memes roll

2017-05-17 23:58 UTC, merged